commands:
  clearchat:
    description: "Clear your chat"
    enabled: true
  servers:
    description: "Shows a list of available servers."
    enabled: true
  setblock:
    description: "Sets a block at the player's location. Usage: /setblock <block_id>"
    enabled: true
  fastmsg:
    description: "Sends a predefined message. Usage: /fastmsg <message_key>"
    enabled: true
  info:
    description: "Shows your player information"
    enabled: true
  redeem:
    description: "Redeem a code for a reward"
    enabled: true
  near:
    description: "Shows nearby players"
    enabled: true
    nearDetectionRadius: 100
  bank:
    description: "Manage your bank account"
    enabled: true
    bank_name: "Waffle Bank"
    min_deposit_money: 1000
    min_withdraw_money: 1000

fast_messages:
  contoh: "Lorem ipsum dolor sit amet"

near-no: "§cNo players found within %d blocks."
near-found: "§aPlayers within %d blocks:"
near-player: "§f%s (%d blocks)"
